import type { Feature, Agent, PricingTier, Stat, Tool } from "@/types";

export const NAV_ITEMS = [
  { label: "Platform", href: "#features" },
  { label: "AI Agents", href: "#agents" },
  { label: "Tools", href: "#tools" },
  { label: "Pricing", href: "#pricing" },
  { label: "Dashboard", href: "/dashboard" },
];

export const STATS: Stat[] = [
  { value: "50+", label: "AI Modules", suffix: "" },
  { value: "10K+", label: "Apps Built", suffix: "" },
  { value: "99.9", label: "Uptime", suffix: "%" },
  { value: "200+", label: "AI Models", suffix: "" },
];

export const FEATURES: Feature[] = [
  {
    id: "brain",
    icon: "🧠",
    title: "Brain LLM Core",
    description: "Multi-model routing, long-term memory, autonomous reasoning, and chain-of-thought simulation with GPT-5 class intelligence.",
    tag: "live",
    color: "blue",
  },
  {
    id: "website",
    icon: "🌐",
    title: "AI Website Builder",
    description: "Prompt → full website in seconds. Drag-and-drop editor, AI SEO, copywriting, responsive layouts, and ecommerce built-in.",
    tag: "live",
    color: "purple",
  },
  {
    id: "app",
    icon: "📱",
    title: "AI Mobile App Builder",
    description: "Generate iOS/Android apps from text. Native export, Stripe integration, push notifications, APK export, one-click deploy.",
    tag: "live",
    color: "cyan",
  },
  {
    id: "game",
    icon: "🎮",
    title: "AI Game Generator",
    description: "Create 2D/3D games with AI NPCs, multiplayer systems, physics engines, story generation, and AI economy balancing.",
    tag: "beta",
    color: "pink",
  },
  {
    id: "design",
    icon: "🎨",
    title: "AI Design Studio",
    description: "Figma-style AI editor. Prompt → UI design, wireframes, component systems, color palettes, and design-to-code export.",
    tag: "live",
    color: "purple",
  },
  {
    id: "video",
    icon: "🎬",
    title: "AI Video Studio",
    description: "Text-to-video, AI avatars, auto-subtitles, TikTok/Shorts creator, voice cloning, AI cinematic editor and transitions.",
    tag: "live",
    color: "pink",
  },
  {
    id: "music",
    icon: "🎵",
    title: "AI Music Studio",
    description: "AI beat generation, vocal synthesis, sound effects, music mastering, mood generation, loop creator, and AI remixing.",
    tag: "beta",
    color: "green",
  },
  {
    id: "image",
    icon: "🖼️",
    title: "AI Image Generator",
    description: "Text-to-image, logo creator, anime generator, 3D renders, product mockups, character creation, and AI upscaling.",
    tag: "live",
    color: "blue",
  },
  {
    id: "automation",
    icon: "⚡",
    title: "AI Workflow Automation",
    description: "Record, replay, and automate any workflow. AI screen actions, autonomous browsing, smart memory graph, code interpreter.",
    tag: "live",
    color: "yellow",
  },
  {
    id: "cloud",
    icon: "☁️",
    title: "Full Stack Cloud Engine",
    description: "Supabase integration, edge functions, GitHub sync, API builder, cloud database, realtime systems, and deployment pipelines.",
    tag: "live",
    color: "cyan",
  },
  {
    id: "analytics",
    icon: "📊",
    title: "AI Analytics Dashboard",
    description: "Real-time monitoring, AI-powered insights, usage metrics, performance tracking, and predictive analytics for all your projects.",
    tag: "live",
    color: "green",
  },
  {
    id: "voice",
    icon: "🎙️",
    title: "AI Voice Assistant",
    description: "Voice operating mode, real-time screen understanding, AI screen actions, workflow recording, and digital twin system.",
    tag: "soon",
    color: "purple",
  },
];

export const AGENTS: Agent[] = [
  {
    id: "marketing",
    name: "ARIA",
    role: "Marketing Agent",
    description: "Creates campaigns, writes copy, manages social media, and optimizes conversion funnels autonomously.",
    capabilities: ["Ad Copy", "Social Media", "SEO", "Analytics"],
    avatar: "📣",
    status: "active",
    color: "#00d4ff",
  },
  {
    id: "coding",
    name: "CODEX",
    role: "Coding Agent",
    description: "Writes, reviews, debugs, and deploys full-stack code. Supports 40+ languages and frameworks.",
    capabilities: ["Full-Stack", "Debug", "Review", "Deploy"],
    avatar: "💻",
    status: "running",
    color: "#8b5cf6",
  },
  {
    id: "research",
    name: "NOVA",
    role: "Research Agent",
    description: "Scans the web, reads documents, synthesizes data, and generates comprehensive reports in real-time.",
    capabilities: ["Web Search", "Reports", "Synthesis", "Citations"],
    avatar: "🔬",
    status: "active",
    color: "#06b6d4",
  },
  {
    id: "finance",
    name: "ATLAS",
    role: "Finance Agent",
    description: "Analyzes financial data, forecasts revenue, manages invoices, and automates accounting workflows.",
    capabilities: ["Forecasting", "Invoices", "P&L", "Automation"],
    avatar: "💰",
    status: "idle",
    color: "#10b981",
  },
  {
    id: "support",
    name: "ECHO",
    role: "Customer Support Agent",
    description: "Handles customer queries 24/7, escalates issues, maintains context across sessions, and learns from interactions.",
    capabilities: ["24/7 Support", "Escalation", "Memory", "Learning"],
    avatar: "🎯",
    status: "active",
    color: "#ec4899",
  },
  {
    id: "seo",
    name: "PULSE",
    role: "SEO Agent",
    description: "Researches keywords, optimizes content, builds backlinks, tracks rankings, and generates SEO reports automatically.",
    capabilities: ["Keywords", "Content", "Backlinks", "Rankings"],
    avatar: "📈",
    status: "running",
    color: "#f59e0b",
  },
];

export const PRICING: PricingTier[] = [
  {
    id: "starter",
    name: "Starter",
    price: 0,
    interval: "forever",
    description: "Begin your AI journey with core features and limited credits.",
    features: [
      "5 AI Projects",
      "100K AI tokens/month",
      "Basic website builder",
      "1 AI Agent",
      "Community support",
      "1GB cloud storage",
    ],
    highlighted: false,
    cta: "Start Free",
  },
  {
    id: "pro",
    name: "Pro",
    price: 49,
    interval: "month",
    description: "Full AI power for serious creators and indie developers.",
    features: [
      "Unlimited AI Projects",
      "5M AI tokens/month",
      "All AI builders (web, app, game)",
      "10 AI Agents",
      "Priority support",
      "50GB cloud storage",
      "AI Design Studio",
      "Video & Music Studio",
      "Custom domain deployment",
    ],
    highlighted: true,
    badge: "Most Popular",
    cta: "Start Pro",
  },
  {
    id: "business",
    name: "Business",
    price: 199,
    interval: "month",
    description: "Enterprise-grade AI OS for teams and businesses.",
    features: [
      "Everything in Pro",
      "Unlimited AI tokens",
      "Unlimited AI Agents",
      "Team collaboration (25 seats)",
      "White-label options",
      "500GB cloud storage",
      "Dedicated AI models",
      "Advanced analytics",
      "SLA + dedicated support",
      "Custom AI training",
    ],
    highlighted: false,
    badge: "Best Value",
    cta: "Start Business",
  },
];

export const TOOLS: Tool[] = [
  {
    id: "website",
    icon: "🌐",
    name: "Website Builder",
    description: "Transform any prompt into a fully functional, SEO-optimized website in under 30 seconds.",
    demos: [
      "Generate a SaaS landing page for my fitness app",
      "Build an ecommerce store for handmade jewelry",
      "Create a portfolio site for a digital artist",
    ],
    color: "blue",
  },
  {
    id: "app",
    icon: "📱",
    name: "App Builder",
    description: "Build native iOS & Android apps with AI. Complete with backend, auth, and one-click deployment.",
    demos: [
      "Build a food delivery app with real-time tracking",
      "Create a meditation app with daily reminders",
      "Generate a social network for photographers",
    ],
    color: "purple",
  },
  {
    id: "game",
    icon: "🎮",
    name: "Game Studio",
    description: "Generate playable 2D and 3D games with AI-driven characters, worlds, and storylines.",
    demos: [
      "Create a RPG with dynamic AI storylines",
      "Build a tower defense game with adaptive AI",
      "Generate a multiplayer racing game",
    ],
    color: "cyan",
  },
];
